package org.bsl.meetingroom.model;

public enum NotificationType {
    BOOKING_CREATED,
    BOOKING_UPDATED,
    BOOKING_APPROVED,
    BOOKING_REJECTED,
    BOOKING_CANCELLED,
    BOOKING_DELETED,
    ROOM_CREATED,
    ROOM_UPDATED,
    ROOM_DELETED,
    USER_CREATED,
    USER_UPDATED,
    USER_STATUS_CHANGED,
    USER_PASSWORD_RESET,
    USER_DELETED,
    DATA_CHANGED
}
